[package]
name = "obsidian-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "8.0.0"
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
# simple_logger = "5.0"
